site_name: MU-ty's Blog
site_url: https://mydomain.org/mysite

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default    # 或 "friendly" / "colorful" 等浅色主题
      noclasses: true        # 使用内联样式，确保无需额外 CSS 即可看到高亮
      guess_lang: false
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.path

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - javascripts/katex-render.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MU-ty

nav:
  - 首页: index.md  
  - LeetCode 刷题:
    - 介绍: leetcode/index.md
    - 哈希:
      - 0001_两数之和: leetcode/哈希/0001.两数之和.md
      - 0049_字母异位词分组: leetcode/哈希/0049. 字母异位词分组.md
      - 0128_最长连续序列: leetcode/哈希/0128. 最长连续序列.md
    - 双指针:
      - 0283_移动零: leetcode/双指针/0283. 移动零.md
      - 0011_盛最多水的容器: leetcode/双指针/0011.盛最多水的容器.md
      - 0015_三数之和: leetcode/双指针/0015.三数之和.md
      - 0042_接雨水: leetcode/双指针/0042.接雨水.md
    - 链表:
      - 0160_相交链表: leetcode/链表/0160. 相交链表.md
      - 0206_反转链表: leetcode/链表/0206. 反转链表.md
      - 0876_链表的中间结点: leetcode/链表/0876.链表的中间结点.md
      - 0234_回文链表: leetcode/链表/0234.回文链表.md
      - 0141_环形链表Ⅰ: leetcode/链表/0141.环形链表Ⅰ.md
      - 0142_环形链表Ⅱ: leetcode/链表/0142. 环形链表 Ⅱ.md
      - 0021_合并两个有序链表: leetcode/链表/0021.合并两个有序链表.md
      - 0023_合并k个升序链表: leetcode/链表/0023.合并k个升序链表.md
      - 0002_两数相加: leetcode/链表/0002.两数相加.md
      - 0086_分隔链表: leetcode/链表/0086.分隔链表.md
      - 0019_删除链表的倒数第N个节点: leetcode/链表/0019.删除链表的倒数第N个结点.md
  

  - Agent: Agent/index.md
  - Backend: Backend/index.md
  - Deep Learning: 
    - Deep Learning/index.md
    - 第四章:
      - 总述: Deep Learning/第四章/index.md
      
  - Frontend: Frontend/index.md
  - Python:
    - 第一章: python/第一章 python程序设计基础.md
    - 第二章: python/第二章 面向对象程序设计.md
    - 第三章: python/第三章 Python中的数据结构、模式匹配和算法理解.md
  - CS168:
    - Home: CS168/home.md
